version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-208-118.compute-1.amazonaws.com
            database: d476qfmmoie80e
            schema: public
            user: nkypbqazlajzgl
            password: 0234fc2146aff38ec04a40a8c7237d6baf92e4ec30c82c980b9c72bb5c4f8ae4
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true