version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-106-93.compute-1.amazonaws.com
            database: dadtrs54q7uv7
            schema: public
            user: clpqtrowclbyjg
            password: b56f38eb41797a4ec31c1c9fd0787724d900712bcc56d811139291ea191e2965
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
